apiVersion: v1
kind: Pod

metadata:
  name: nginx-pod

spec:
  containers:
   -  name: nginx-container
      image: nginx
      ports:
        - containerPort: 80

#ローカルからnginxに接続したい場合
#sudo kubectl port-forward pod/[pod名] [ローカルポート]:[パッドポート]